import "./globals.css";

import { PT_Sans } from "next/font/google";
import Nav from "./components/structure/Nav/Nav";
import Footer from "./components/structure/Footer/Footer";

const ptSans = PT_Sans({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Dm Taller</title>
      </head>

      <body className={ptSans.className}>{children}</body>
    </html>
  );
}
